name: '🛠 Build'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: '🛠 Build'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: '📚 checkout'
        uses: actions/checkout@v2.3.4
      - name: '🟢 node v ${{ matrix.node-version }}'
        uses: actions/setup-node@v1.1.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: '📦 install'
        run: npm ci
      - name: '🛠 build'
        run: |
          npm run build
          sh -c '[ -f ./dist/bundle.cjs.js ]'
          sh -c '[ -f ./dist/bundle.esm.js ]'
      - name: '🧪 test'
        run: npm run test:coverage
      - name: '👖 coveralls'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
